[package]

name = "357"
version = "0.0.1"
authors = ["Urchenko <urchenko88@gmail.com>"]

[dependencies]
time = "*"

[profile.release]
opt-level = 3 
debug = false
rpath = false
lto = false

[profile.test]
opt-level = 3
debug = true
rpath = false
lto = false
